apiVersion: ${API_VERSION}
kind: ${KIND}
metadata:
  name: ${NAME}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: ${PRIMARY_CONTAINER}
          image: ghcr.io/hrntknr/sh:full
          imagePullPolicy: Always
          command:
            - /usr/local/bin/start-sshd
          ports:
            - containerPort: 22
              name: ssh
              protocol: TCP
