#!/bin/bash

set -eu

DOTFILES_PATH="${HOME}/.dotfiles"
REPOSITORY="https://github.com/hrntknr/dotfiles.git"

INSTALL_BREW="vim tmux"
INSTALL_APT="git zsh vim tmux"
INSTALL_DNF="git zsh vim tmux"
INSTALL_YUM="git zsh vim tmux"

SIMLINK=(".editorconfig" ".eslintrc.json" ".tmux.conf" ".vimrc" ".zprofile" ".zshrc")

case ${OSTYPE} in
  darwin*)
    id=$(id -u)
    if [ $id -eq 0 ]
    then
      echo "Don't run as root."
      exit 1
    fi

    if [ ! "$(type brew)" ]
    then
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    eval "brew install ${INSTALL_BREW}"
    ;;
  linux*)
    id=$(id -u)
    if [ $id -ne 0 ]
    then
      echo "Please run as root."
      exit 1
    fi

    if type apt-get
    then
      apt-get update
      apt-get upgrade
      eval "apt-get install -y ${INSTALL_APT}"
    elif type dnf
    then
      dnf update
      eval "dnf install -y ${INSTALL_DNF}"
    elif type yum
    then
      yum update
      eval "yum install -y ${INSTALL_YUM}"
    fi
    ;;
esac

if [ ! -d ${HOME}/.nvm ] && [ ! "$(type nvm)" ]
then
  sudo -u $(logname) git clone git://github.com/creationix/nvm.git ${HOME}/.nvm
fi

if [ ! -d ${HOME}/.pyenv ] && [ ! "$(type pyenv)" ]
then
  sudo -u $(logname) git clone https://github.com/pyenv/pyenv.git ${HOME}/.pyenv
fi

if [ ! -d ${HOME}/.rbenv ] && [ ! "$(type rbenv)" ]
then
  sudo -u $(logname) git clone https://github.com/rbenv/rbenv.git ${HOME}/.rbenv
fi

if [ -d ${DOTFILES_PATH} ]
then
  cd ${DOTFILES_PATH}
  sudo -u $(logname) git pull
else
  sudo -u $(logname) git clone ${REPOSITORY} ${DOTFILES_PATH}
  cd ${DOTFILES_PATH}
fi

for item in ${SIMLINK[@]}
do
  if [ ! -e ${HOME}/${item} ]
  then
    sudo -u $(logname) ln -s ${DOTFILES_PATH}/${item} ${HOME}/${item}
  fi
done
