#!/bin/bash

set -eu

DOTFILES_PATH="${HOME}/.dotfiles"
REPOSITORY="https://github.com/hrntknr/dotfiles.git"

INSTALL_BREW="vim tmux neovim/neovim/neovim"
INSTALL_APT="git zsh vim tmux"
INSTALL_DNF="git zsh vim tmux"
INSTALL_YUM="git zsh vim tmux"

SIMLINK=(".editorconfig" ".eslintrc.json" ".tmux.conf" ".vimrc" ".zprofile" ".zshrc" ".config@nvim@dein-plugins.toml" ".config@nvim@init.vim")

case ${OSTYPE} in
  darwin*)
    id=$(id -u)
    if [ $id -eq 0 ]
    then
      echo "Don't run as root."
      exit 1
    fi

    if [ ! "$(type brew)" ]
    then
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    set +e
    eval "brew install ${INSTALL_BREW}"
    set -e
    ;;
  linux*)
    id=$(id -u)
    if [ $id -ne 0 ]
    then
      echo "Please run as root."
      exit 1
    fi

    if type apt-get
    then
      apt-get update
      apt-get upgrade -y
      apt-get install -y ${INSTALL_APT}
    elif type dnf
    then
      dnf update -y
      dnf install -y ${INSTALL_DNF}
    elif type yum
    then
      yum update -y
      yum install -y ${INSTALL_YUM}
    fi
    ;;
esac

if [ ! -d ${HOME}/.nvm ] && [ ! "$(type nvm)" ]
then
  sudo -u $(logname) git clone https://github.com/creationix/nvm.git ${HOME}/.nvm
fi

if [ ! -d ${HOME}/.pyenv ] && [ ! "$(type pyenv)" ]
then
  sudo -u $(logname) git clone https://github.com/pyenv/pyenv.git ${HOME}/.pyenv
fi

if [ ! -d ${HOME}/.rbenv ] && [ ! "$(type rbenv)" ]
then
  sudo -u $(logname) git clone https://github.com/rbenv/rbenv.git ${HOME}/.rbenv
fi

if [ -d ${DOTFILES_PATH} ]
then
  cd ${DOTFILES_PATH}
  sudo -u $(logname) git pull
else
  sudo -u $(logname) git clone ${REPOSITORY} ${DOTFILES_PATH}
  cd ${DOTFILES_PATH}
fi

for item in ${SIMLINK[@]}
do
  path="${HOME}/${item//@//}"
  dir=${path%/*}
  file=${path##*/}
  if [ ! -e ${dir} ]
  then
    sudo -u $(logname) mkdir -p ${dir}
  fi
  if [ ! -e ${path} ]
  then
    sudo -u $(logname) ln -s ${DOTFILES_PATH}/${item} ${path}
  fi
done
