apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patch.yaml
secretGenerator:
  - name: ${NAME}-host-keys
    files:
      - ssh_host_ed25519_key
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true
