apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ${NAME}
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: ${NAME}
          image: ghcr.io/hrntknr/sh:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 22
              name: ssh
              protocol: TCP
