apiVersion: ${BASE_API_VERSION}
kind: ${BASE_KIND}
metadata:
  name: ${NAME}
spec:
  template:
    spec:
      containers:
        - name: ${NAME}
          resources:
            limits:
              preferred.jp/mncore2: 1
            requests:
              preferred.jp/mncore2: 1
