[settings]
auto_install = false
offline = true

[tools]
fzf = "latest"
neovim = "latest"
tmux = "latest"
yq = "latest"
jq = "latest"
gh = "latest"
ghq = "latest"
sops = "latest"
age = "latest"
uv = "latest"
pipx = "latest"
go = "latest"
rust = "latest"
kubectl = "latest"
kustomize = "latest"
helm = "latest"
flux2 = "latest"
stern = "latest"
k9s = "latest"
kubeseal = "latest"
"aqua:int128/kubelogin" = "latest"
"aqua:cilium/cilium-cli" = "latest"
"aqua:cilium/hubble" = "latest"
krew = "latest"
opencode = "latest"
claude = "latest"
codex = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:tofuutils/tenv" = "latest"
ansible = "latest"
gcloud = "latest"
aws = "latest"
