[tools]
fzf = "0.73.1"
neovim = "0.12.3"
tmux = "3.6b"
yq = "4.53.3"
jq = "1.8.2"
gh = "2.95.0"
ghq = "1.10.1"
sops = "3.13.1"
age = "1.3.1"
uv = "0.11.23"
pipx = "1.14.1"
go = "1.26.4"
rust = "1.96.0"
kubectl = "1.36.2"
kustomize = "5.8.1"
helm = "4.2.2"
flux2 = "2.9.0"
stern = "1.34.0"
k9s = "0.51.0"
kubeseal = "0.38.1"
"aqua:int128/kubelogin" = "1.36.2"
"aqua:cilium/cilium-cli" = "0.19.4"
"aqua:cilium/hubble" = "1.19.4"
krew = "0.5.0"
opencode = "1.17.9"
claude = "2.1.185"
codex = "0.137.0"
node = "24.17.0"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:tofuutils/tenv" = "4.14.8"
ansible = "14.1.0"
gcloud = "571.0.0"
aws = "2.35.9"
