name: default
k8s: true
rules:
  - allow(r, ~/.local)
  - allow(r, ~/.gitconfig)
  - allow(r, ~/.gitignore_global)
  - allow(r, ~/.config/gh)
  - allow(rw, ~/.ssh/known_hosts)
  - allow(r, ~/.kube/kuberc)
  - allow(rw, ~/.claude)
  - allow(rw, ~/.claude-pfn)
  - allow(rw, ~/.claude.json)
  - allow(rw, ~/.codex)
  - allow(rw, ~/.nvm)
  - allow(rw, ~/work/go/pkg/mod)
  - allow(rw, ~/Library/Caches/go-build)
  - allow(rw, ~/.dotfiles)
  - deny(rw, ~/.*)
  - allow(rw, ${WORK_DIR})
  - allow(r, /)
