name: default
docker:
  - allow(rw, rootless)
  - allow(r, *)
ssh:
  - allow(github.com)
  - allow(*.hrntknr.net)
k8s:
  - allow(rw, pear)
  - allow(rw, test)
  - allow(r, *)
rules:
  - allow(rw, ~/.claude)
  - allow(rw, ~/.claude-pfn)
  - allow(rw, ~/.claude.json)
  - allow(rw, ~/.codex)
  - allow(rw, ~/.opencode)
  - allow(rw, ~/.cache/opencode)
  - allow(rw, ~/.local/share/opencode)
  - allow(rw, ~/.local/state/opencode)
  - allow(rw, ~/.nvm)
  - allow(rw, ~/work/go/pkg/mod)
  - allow(rw, ~/Library/Caches/go-build)
  - allow(rw, ~/.dotfiles)

  - allow(r, ~/.config/opencode)

  - allow(r, ~/.local)
  - allow(r, ~/.gitconfig)
  - allow(r, ~/.gitignore_global)
  - allow(r, ~/.config/gh)
  - allow(r, ~/.kube/kuberc)

  - allow(r, ~/.zshrc)
  - allow(r, ~/.zshrc.local)
  - allow(r, ~/.zprofile)
  - allow(r, ~/.zprofile.local)

  - deny(rw, /var/run/docker.sock)
  - deny(rw, ~/.*)
  - allow(rw, ${WORK_DIR})
  - allow(r, /)
