"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
${custom.hostname}\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$kubernetes\
$line_break\
$jobs\
$container\
$netns\
$character
"""

add_newline = true
hostname.disabled = true
aws.disabled = true
azure.disabled = true
gcloud.disabled = true

[username]
show_always = true
format = "[$user@]($style)"
style_user = "white"
style_root = "red"

[custom.hostname]
command = '''
hostname=$(hostname)
if [ -n "$SHELL_COLOR" ]; then
  color_code=$SHELL_COLOR
else
  color_code=$((16#$(printf '%s' "$hostname" | md5sum | cut -c1-2)))
fi
printf '\e[38;05;%dm%s\e[0m\n' "$color_code" "$hostname"
'''
when = "true"
format = '$output '

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1
style = "white"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
format = '[\($hash$tag\)]($style) '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[kubernetes]
disabled = false
format = '[$symbol$context]($style) '
style = "dimmed cyan"
