name: Docker PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - full
          - slim
        platform:
          - { name: linux/amd64, runner: ubuntu-24.04, suffix: amd64 }
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: ${{ matrix.platform.name }}
          build-args: |
            DOTFILES_PROFILE=${{ matrix.profile }}
          secrets: |
            github_token=${{ github.token }}
          push: false
